name: app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_svg: ^0.14.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/fb.svg
    - assets/icons/google.svg
    - assets/icons/twitter.svg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Crimson
      fonts:
        - asset: assets/fonts/Crimson_Text/CrimsonText-Regular.ttf
        - asset: assets/fonts/Crimson_Text/CrimsonText-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Crimson_Text/CrimsonText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Crimson_Text/CrimsonText-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Crimson_Text/CrimsonText-Bold.ttf
          weight: 700
        - asset: assets/fonts/Crimson_Text/CrimsonText-BoldItalic.ttf
          style: italic
          weight: 700
    - family: PT
      fonts:
        - asset: assets/fonts/PT_Serif/PTSerif-Regular.ttf
        - asset: assets/fonts/PT_Serif/PTSerif-ITalic.ttf
          style: italic
        - asset: assets/fonts/PT_Serif/PTSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/PT_Serif/PTSerif-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Light.ttf
          weight: 300
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Regular.ttf
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Bold.ttf
          weight: 700

